@baseUrl = http://127.0.0.1:30005/api
@apiUrl = {{baseUrl}}/books
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIyZDRhOTUzLTMyOGItNDliMC1iMWY3LTdkOTRhMzQzZWQyYyIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzMzNDU0NzksImV4cCI6MTY4MjM0NTQ3OX0.ec2dfNDtCl5yltUfIegwYpwF39abObEOBLcKVzlBh-0


# GET {{apiUrl}}?tags=1,2
# GET {{apiUrl}}?categories=4
# GET {{apiUrl}}?categories=4,8
# GET {{apiUrl}}?publisherIds=3,4
# GET {{apiUrl}}?author=2
# GET {{apiUrl}}?author=1,2
# GET {{apiUrl}}?author=1&limit=4&page=1
GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/a3c975f9-2fe9-415f-aa5e-bd4a76c43faf
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/111/tags
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/111/similar
Content-Type: application/json
Authorization: Bearer {{token}}