@baseUrl = http://127.0.0.1:30005/api
@apiUrl = {{baseUrl}}/books
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBhZWE1MDYxLWFlNjUtNGFhNi1hOWU5LTVlZjkzNjc2YTU3ZiIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzMwMjIwOTgsImV4cCI6MTY4MjAyMjA5OH0.tY8jcnDnWZKiYjfF0_0yCsv5DfffCxTwCryOa2r_qMo


# GET {{apiUrl}}?tags=2
# GET {{apiUrl}}?tags=1,2
# GET {{apiUrl}}?categories=4
# GET {{apiUrl}}?categories=4,8
# GET {{apiUrl}}?publisherIds=3,4
# GET {{apiUrl}}?author=2
# GET {{apiUrl}}?author=1,2
GET {{apiUrl}}?author=1,2&limit=1&page=2
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/111
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/111/tags
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/111/similar
Content-Type: application/json
Authorization: Bearer {{token}}