@baseUrl = http://127.0.0.1:30005/api
@apiUrl = {{baseUrl}}/categories

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhY2VhMTA2LTc2MmItNGUzNS1hNThkLWVjZTI5M2MyOTlkMyIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzM4NDUzMDEsImV4cCI6MTY4Mjg0NTMwMX0.f4igOP_QDijzP8FBXfqLJddv_NaoIm_7pBfx4c3P29o

GET {{apiUrl}}
Content-Type: application/json

###
GET {{apiUrl}}/98b473ad-ae03-4344-8bea-169540b5cd04
Content-Type: application/json

###
GET {{apiUrl}}/8903d54c-eb04-4668-97ff-f9f959b4cb8d/books?limit=1&page=2
Content-Type: application/json


###
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : ,
  "parentId" : 
}

###
PUT {{apiUrl}}/4687dca5-a172-4fec-a5fa-0ea8a20f9ebc
Content-Type: application/json
Authorization: Bearer {{token}}

{
"name": "ترس",
 "parentId" : "d9eb4683-8b4f-4e04-841e-2e290ee2deff"
}