@baseUrl = http://127.0.0.1:30005/api
@apiUrl = {{baseUrl}}/tags
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhY2VhMTA2LTc2MmItNGUzNS1hNThkLWVjZTI5M2MyOTlkMyIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzM4NDUzMDEsImV4cCI6MTY4Mjg0NTMwMX0.f4igOP_QDijzP8FBXfqLJddv_NaoIm_7pBfx4c3P29o

GET {{apiUrl}}
Content-Type: application/json

###
GET {{apiUrl}}/50891fe0-9a2c-49e1-a2b5-075dd0701170
Content-Type: application/json

###
GET {{apiUrl}}/ad9313ae-5b9d-4b4f-8919-e4565e2bf11c/books?limit=1&page=1
Content-Type: application/json

###
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

###
PUT {{apiUrl}}/
Content-Type: application/json
Authorization: Bearer {{token}}

{

}