@baseUrl = http://127.0.0.1:30005/api
@apiUrl = {{baseUrl}}/publishers
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhY2VhMTA2LTc2MmItNGUzNS1hNThkLWVjZTI5M2MyOTlkMyIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzM4NDUzMDEsImV4cCI6MTY4Mjg0NTMwMX0.f4igOP_QDijzP8FBXfqLJddv_NaoIm_7pBfx4c3P29o


GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/9d539539-fcb0-4711-a53d-5e674345c29b
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/9d539539-fcb0-4711-a53d-5e674345c29b/books?limit=1
Content-Type: application/json
