@baseUrl = http://185.128.137.193:30008/api
@apiUrl = {{baseUrl}}/auth

POST {{apiUrl}}
Content-Type: application/json

{
  "phone": "09333950889"
}

###
POST {{apiUrl}}/0aea5061-ae65-4aa6-a9e9-5ef93676a57f
Content-Type: application/json

{
  "confirmCode": "700984",
  "skipCaptcha": true
}

###
POST http://localhost:30002/api/auth/register
Content-Type: application/json

{
  "phone": "09355459698",
  "skipCaptcha": true
}

###

POST {{apiUrl}}/login
Content-Type: application/json

{
  "username": "09333950889",
  "password": "1230",
  "skipCaptcha": true
}