@baseUrl = http://185.128.137.193:30008/api
@apiUrl = {{baseUrl}}/roles

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhOGQ5MGIzLWQwZjQtNDc2MC05ZGI0LTQ3YzFkYTA3ZGM0OSIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzQzNjYzMTAsImV4cCI6MTY4MzM2NjMxMH0.SkAezgrMcOOp4wXILtuS1fMx4iFomOmH2dFe-taHAAU

GET {{apiUrl}}/permissions
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/c95cf70a-39e7-4e3f-82f5-acbf7210bd10
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "name" : "manager1",
 "permissions" : ["SEE_ROLES"]
}
