@baseUrl = http://localhost:30005/api
# @baseUrl = https://sanab.farzinahmadi.com/api
@apiUrl = {{baseUrl}}/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhZWNlNTVhLWJkNWItNGU2Yi04YmFjLWZhZTUxZmZjYzhmMyIsInBob25lIjoiMDkzMDQ0MjgwMDYiLCJpYXQiOjE2Nzg4NTczODMsImV4cCI6MTY4Nzg1NzM4M30.FjeQylwbTNNo3p5zFCiHUs5h2k3UxBku6E8PoA1163M

# GET {{apiUrl}}
# GET {{apiUrl}}?limit=2
GET {{apiUrl}}?s=ی
# GET {{apiUrl}}?s=ی&limit=2
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/7acea106-762b-4e35-a58d-ece293c299d3
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "phone": "09124439654",
    "email": "n98ahmadian@gmail.com",
    "firstName": "Naiem",
    "lastName": "Ahmadian",
    "imageId": "1",
    "status": 1,
    "brand" : "Dior",
    "roleId": "21ffc1f8-c672-4315-9d64-e96c33fe0ba3",
    "car" : "pejo 206"
}

###
PUT {{apiUrl}}/89683895-e47f-40c7-9f73-6f92a54c24db
Content-Type: application/json
Authorization: Bearer {{token}}

{
"email": "t@m30.com"
}

###

GET {{apiUrl}}/aaece55a-bd5b-4e6b-8bac-fae51ffcc8f3/books
Content-Type: application/json
Authorization: Bearer {{token}}
