@baseUrl = http://185.128.137.193:30008/api
@apiUrl = {{baseUrl}}/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhOGQ5MGIzLWQwZjQtNDc2MC05ZGI0LTQ3YzFkYTA3ZGM0OSIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzQzNjYzMTAsImV4cCI6MTY4MzM2NjMxMH0.SkAezgrMcOOp4wXILtuS1fMx4iFomOmH2dFe-taHAAU

GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/7acea106-762b-4e35-a58d-ece293c299d3
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "phone": "09124439654",
    "email": "n98ahmadian@gmail.com",
    "firstName": "Naiem",
    "lastName": "Ahmadian",
    "imageId": "1",
    "status": 1,
    "brand" : "Dior",
    "roleId": "21ffc1f8-c672-4315-9d64-e96c33fe0ba3",
    "car" : "pejo 206"
}

###
PUT {{apiUrl}}/6987dc6e-9955-49da-8847-1e1a8a1c2d70
Content-Type: application/json
Authorization: Bearer {{token}}

{
"brand": "Gucci"
}