@baseUrl = http://localhost:30005/api
# @baseUrl = https://sanab.farzinahmadi.com/api
@apiUrl = {{baseUrl}}/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5NjgzODk1LWU0N2YtNDBjNy05ZjczLTZmOTJhNTRjMjRkYiIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzU1OTk1MTksImV4cCI6MTY4NDU5OTUxOX0.Nfkk17QIBmqV9fbUfC39DO4lvp4Rjp6V8wKlQ1Waye8

GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/7acea106-762b-4e35-a58d-ece293c299d3
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "phone": "09124439654",
    "email": "n98ahmadian@gmail.com",
    "firstName": "Naiem",
    "lastName": "Ahmadian",
    "imageId": "1",
    "status": 1,
    "brand" : "Dior",
    "roleId": "21ffc1f8-c672-4315-9d64-e96c33fe0ba3",
    "car" : "pejo 206"
}

###
PUT {{apiUrl}}/89683895-e47f-40c7-9f73-6f92a54c24db
Content-Type: application/json
Authorization: Bearer {{token}}

{
"email": "t@m30.com"
}