@baseUrl = http://127.0.0.1:30005/api
@apiUrl = {{baseUrl}}/books
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhY2VhMTA2LTc2MmItNGUzNS1hNThkLWVjZTI5M2MyOTlkMyIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzM4NDUzMDEsImV4cCI6MTY4Mjg0NTMwMX0.f4igOP_QDijzP8FBXfqLJddv_NaoIm_7pBfx4c3P29o

POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "ssssss",
  "image": "42fc95de-886e-4c80-85ca-25ad9dc8c3a9",
  "content": "ssswwww",
  "publishedYear": 1394,
  "price": 250000,
  "offPrice": {
    "type": 1,
    "amount": 1000,
    "startDate": "1401-05-03",
    "endDate": "1401-05-05"
  },
  "publisher": "abeaa0a5-dce4-4d32-be14-c743ac0f590b",
  "categories": [
    "94be2d55-3479-429d-9a82-4f28554013c1"
  ],
  "tags": [
    "fd86f852-ae76-48df-8778-ea8b8a42787c", 
    "50891fe0-9a2c-49e1-a2b5-075dd0701170"
  ],
  "authors": {
    "writer": ["aaa", "bbb"],
    "author": ["aaa", "bbb"],
    "translator": ["aaa", "bbb"],
    "resercher": ["aaa", "bbb"],
    "narrator": ["aaa", "bbb"]
  }
}

###

# GET {{apiUrl}}?tags=1,2
# GET {{apiUrl}}?categories=4
# GET {{apiUrl}}?categories=4,8
# GET {{apiUrl}}?publisherIds=3,4
# GET {{apiUrl}}?authors=2
# GET {{apiUrl}}?authors=1,2
# GET {{apiUrl}}?authors=1&limit=4&page=1
# GET {{apiUrl}}?author=2
# GET {{apiUrl}}?author=1,2
# GET {{apiUrl}}?tags=1,2&categories=8&limit=3&page=1
# GET {{apiUrl}}?author=1&limit=4&page=1
# GET {{apiUrl}}?limit=2&page=2
# GET {{apiUrl}}?authors=2
# GET {{apiUrl}}?authors=1,2
# GET {{apiUrl}}?authors=1&limit=4&page=1
GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/6230d512-e27b-4c73-a37b-58bb1c2c9a4a
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/a3c975f9-2fe9-415f-aa5e-bd4a76c43faf/similar
Content-Type: application/json
Authorization: Bearer {{token}}