@baseUrl = http://127.0.0.1:30005/api
@apiUrl = {{baseUrl}}/books
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhOGMwMjViLTcwOWEtNDgxNS05MzI5LWM4ZDM1YjZmMmMxYSIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzM0MjYyODksImV4cCI6MTY4MjQyNjI4OX0.v8t5p8zUimoE5o9RhjrmTp3QTFutMdmm95pcpioStK0

# GET {{apiUrl}}?tags=1,2
# GET {{apiUrl}}?categories=4
# GET {{apiUrl}}?categories=4,8
# GET {{apiUrl}}?publisherIds=3,4
# GET {{apiUrl}}?authors=2
# GET {{apiUrl}}?authors=1,2
# GET {{apiUrl}}?authors=1&limit=4&page=1
# GET {{apiUrl}}?author=2
# GET {{apiUrl}}?author=1,2
# GET {{apiUrl}}?tags=1,2&categories=8&limit=3&page=1
# GET {{apiUrl}}?author=1&limit=4&page=1
# GET {{apiUrl}}?limit=2&page=2
# GET {{apiUrl}}?authors=2
# GET {{apiUrl}}?authors=1,2
# GET {{apiUrl}}?authors=1&limit=4&page=1
GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/869cd8e9-276e-4e82-9795-47ed4c7c7dc7
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/a3c975f9-2fe9-415f-aa5e-bd4a76c43faf/similar
Content-Type: application/json
Authorization: Bearer {{token}}