@baseUrl = http://127.0.0.1:30005/api
@apiUrl = {{baseUrl}}/books
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhY2VhMTA2LTc2MmItNGUzNS1hNThkLWVjZTI5M2MyOTlkMyIsInBob25lIjoiMDkzMzM5NTA4ODkiLCJpYXQiOjE2NzM4NDUzMDEsImV4cCI6MTY4Mjg0NTMwMX0.f4igOP_QDijzP8FBXfqLJddv_NaoIm_7pBfx4c3P29o

POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "authors": {
    "author": [
      "9397fbbe-573b-46ad-868c-09df6ab0b0f1", 
      "0a047a33-c8b3-4d17-9e48-504d672f9679"
    ],
    "narrator": [
      "f7515aa2-8b3a-469f-a397-c92c5ec2eabb", 
      "7c49a02d-892d-4061-bd81-0e3a298fc1ee"
    ],
    "resercher": [
      "7c49a02d-892d-4061-bd81-0e3a298fc1ee",
      "cf7c8cba-b1f7-4a9c-ab8f-5aa4101aa8d7"
    ],
    "translator": [
      "b57657f3-661f-462a-9370-2c5ca62fa2b4", 
      "0402e2c9-9312-4cf4-a5d0-f64e05dc9e99"
    ],
    "writer": ["0a047a33-c8b3-4d17-9e48-504d672f9679"]
  },
  "categories": [
    "94be2d55-3479-429d-9a82-4f28554013c1"
  ],
  "content": "ssswwww",
  "files": {
    "epub": {
      "main": "bbbb",
      "sample": "aaaaaaa"
    },
    "pdf": {
      "main": "bbbb",
      "sample": "aaaaaaa"
    },
    "sound": {
      "main": "0a047a33-c8b3-4d17-9e48-504d672f9679",
      "sample": "wwwww"
    }
  },
  "image": "42fc95de-886e-4c80-85ca-25ad9dc8c3a9",
  "name": "ssssss",
  "offPrice": {
    "type": 1,
    "amount": 1000,
    "startDate": "1401-05-03",
    "endDate": "1401-05-05"
  },
  "price": 250000,
  "publishedYear": 1394,
  "publisher": "abeaa0a5-dce4-4d32-be14-c743ac0f590b",
  "tags": [
    "fd86f852-ae76-48df-8778-ea8b8a42787c", 
    "50891fe0-9a2c-49e1-a2b5-075dd0701170"
  ]
}

###

# GET {{apiUrl}}?tags=1,2
# GET {{apiUrl}}?categories=4
# GET {{apiUrl}}?categories=4,8
# GET {{apiUrl}}?publisherIds=3,4
# GET {{apiUrl}}?authors=2
# GET {{apiUrl}}?authors=1,2
# GET {{apiUrl}}?authors=1&limit=4&page=1
# GET {{apiUrl}}?author=2
# GET {{apiUrl}}?author=1,2
# GET {{apiUrl}}?tags=1,2&categories=8&limit=3&page=1
# GET {{apiUrl}}?author=1&limit=4&page=1
# GET {{apiUrl}}?limit=2&page=2
# GET {{apiUrl}}?authors=2
# GET {{apiUrl}}?authors=1,2
# GET {{apiUrl}}?authors=1&limit=4&page=1
GET {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/049f2479-f8f3-4a9e-8004-3159c42c68d6
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/a3c975f9-2fe9-415f-aa5e-bd4a76c43faf/similar
Content-Type: application/json
Authorization: Bearer {{token}}